/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AlertaOrcamentoDto {
  /**
   * Tipo do alerta
   */
  tipo: AlertaOrcamentoDto.TipoEnum;
  /**
   * Categoria relacionada
   */
  categoria?: string;
  /**
   * Título do alerta
   */
  titulo: string;
  /**
   * Descrição detalhada
   */
  descricao: string;
  /**
   * Valor envolvido no alerta
   */
  valorEnvolvido?: number;
  /**
   * Ação recomendada
   */
  acao?: string;
}
export namespace AlertaOrcamentoDto {
  export type TipoEnum = "info" | "warning" | "error" | "success";
  export const TipoEnum = {
    Info: "info" as TipoEnum,
    Warning: "warning" as TipoEnum,
    Error: "error" as TipoEnum,
    Success: "success" as TipoEnum,
  };
}
