/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EvolucaoMensalDto } from "./evolucaoMensalDto";
import { MetricasAvancadasDto } from "./metricasAvancadasDto";
import { ProjecaoMesDto } from "./projecaoMesDto";
import { InsightFinanceiroDto } from "./insightFinanceiroDto";

export interface AnalyticsTendenciasDataDto {
  /**
   * Evolução mensal histórica
   */
  evolucaoMensal: Array<EvolucaoMensalDto>;
  /**
   * Projeção para o mês atual
   */
  projecaoMesAtual: ProjecaoMesDto;
  /**
   * Métricas avançadas
   */
  metricas: MetricasAvancadasDto;
  /**
   * Insights financeiros automatizados
   */
  insights: Array<InsightFinanceiroDto>;
}
