/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrcamentoCategoriaDto } from "./orcamentoCategoriaDto";
import { OrcamentoGeralDto } from "./orcamentoGeralDto";
import { SaudeFinanceiraDto } from "./saudeFinanceiraDto";
import { AlertaOrcamentoDto } from "./alertaOrcamentoDto";

export interface AnalyticsOrcamentoDataDto {
  /**
   * Saúde financeira geral
   */
  saudeFinanceira: SaudeFinanceiraDto;
  /**
   * Orçamento geral do mês
   */
  orcamentoGeral: OrcamentoGeralDto;
  /**
   * Orçamento por categoria
   */
  orcamentoCategorias: Array<OrcamentoCategoriaDto>;
  /**
   * Alertas de orçamento
   */
  alertas: Array<AlertaOrcamentoDto>;
}
