/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategoriaAnalyticsDto } from "./categoriaAnalyticsDto";
import { TotalMesAnteriorDto } from "./totalMesAnteriorDto";

export interface AnalyticsCategoriasDataDto {
  /**
   * Lista de categorias com analytics
   */
  categorias: Array<CategoriaAnalyticsDto>;
  /**
   * Total geral do período
   */
  totalGeral: number;
  /**
   * Comparação com mês anterior
   */
  mesAnterior: TotalMesAnteriorDto;
}
