/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ParcelaAbertaDto } from "./parcelaAbertaDto";
import { LembreteTransacaoDto } from "./lembreteTransacaoDto";
import { PadraoDiarioDto } from "./padraoDiarioDto";
import { TransacaoRecorrenteDto } from "./transacaoRecorrenteDto";

export interface AnalyticsPadroesTemporaisDataDto {
  /**
   * Padrões de gastos por dia da semana
   */
  padroesDiarios: Array<PadraoDiarioDto>;
  /**
   * Transações recorrentes identificadas
   */
  transacoesRecorrentes: Array<TransacaoRecorrenteDto>;
  /**
   * Lembretes de transações
   */
  lembretes: Array<LembreteTransacaoDto>;
  /**
   * Parcelas em aberto
   */
  parcelasAbertas: Array<ParcelaAbertaDto>;
}
