/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResumoMeiosPagamentoDto } from "./resumoMeiosPagamentoDto";
import { MeioPagamentoAnalyticsDto } from "./meioPagamentoAnalyticsDto";
import { FormaPagamentoAnalyticsDto } from "./formaPagamentoAnalyticsDto";

export interface AnalyticsMeiosPagamentoDataDto {
  /**
   * Analytics por meio de pagamento
   */
  meiosPagamento: Array<MeioPagamentoAnalyticsDto>;
  /**
   * Analytics por forma de pagamento
   */
  formasPagamento: FormaPagamentoAnalyticsDto;
  /**
   * Resumo geral
   */
  resumo: ResumoMeiosPagamentoDto;
}
