/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Categoria {
  id: string;
  nome: string;
  tipo: Categoria.TipoEnum;
  icone: string;
  tetoGasto: number;
  cor: string;
  createdAt: string;
}
export namespace Categoria {
  export type TipoEnum = "despesa" | "receita";
  export const TipoEnum = {
    Despesa: "despesa" as TipoEnum,
    Receita: "receita" as TipoEnum,
  };
}
