/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MaiorTransacaoDto } from "./maiorTransacaoDto";
import { MesAnteriorDto } from "./mesAnteriorDto";

export interface CategoriaAnalyticsDto {
  /**
   * ID da categoria
   */
  id: string;
  /**
   * Nome da categoria
   */
  nome: string;
  /**
   * Tipo da categoria
   */
  tipo: CategoriaAnalyticsDto.TipoEnum;
  /**
   * Ícone da categoria
   */
  icone: string;
  /**
   * Cor da categoria
   */
  cor: string;
  /**
   * Valor total movimentado na categoria
   */
  valorTotal: number;
  /**
   * Número de transações
   */
  numeroTransacoes: number;
  /**
   * Percentual do total geral
   */
  percentualDoTotal: number;
  /**
   * Teto de gasto configurado
   */
  tetoGasto: number;
  /**
   * Percentual do teto utilizado
   */
  percentualTeto: number;
  /**
   * Se o teto foi ultrapassado
   */
  tetoUltrapassado: boolean;
  /**
   * Dados do mês anterior
   */
  mesAnterior: MesAnteriorDto;
  /**
   * Maior transação da categoria
   */
  maiorTransacao: MaiorTransacaoDto;
}
export namespace CategoriaAnalyticsDto {
  export type TipoEnum = "receita" | "despesa";
  export const TipoEnum = {
    Receita: "receita" as TipoEnum,
    Despesa: "despesa" as TipoEnum,
  };
}
