/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { LinhaConfirmacao } from "./linhaConfirmacao";

export interface ConfirmarImportacaoRequest {
  /**
   * Linhas marcadas para importar (já revisadas)
   */
  linhas: Array<LinhaConfirmacao>;
  /**
   * Tag aplicada a todas as transações importadas (normalizada).
   */
  tagEmLote?: string;
}
