/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CreateCategoriaRequest {
  /**
   * Nome da categoria
   */
  nome: string;
  /**
   * Tipo da categoria (despesa ou receita)
   */
  tipo: CreateCategoriaRequest.TipoEnum;
  /**
   * Ícone da categoria
   */
  icone?: string;
  /**
   * Cor da categoria em hexadecimal
   */
  cor?: string;
}
export namespace CreateCategoriaRequest {
  export type TipoEnum = "despesa" | "receita";
  export const TipoEnum = {
    Despesa: "despesa" as TipoEnum,
    Receita: "receita" as TipoEnum,
  };
}
