/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CreateRecorrenciaRequest {
  descricao: string;
  valor: number;
  /**
   * Dia do vencimento (1-31)
   */
  diaVencimento: number;
  frequencia?: CreateRecorrenciaRequest.FrequenciaEnum;
  categoriaId?: string;
  /**
   * Meio de pagamento (\"pagar com\")
   */
  meioPagamentoId?: string;
  pessoaId?: string;
}
export namespace CreateRecorrenciaRequest {
  export type FrequenciaEnum = "mensal";
  export const FrequenciaEnum = {
    Mensal: "mensal" as FrequenciaEnum,
  };
}
