/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface DistribuicaoParcelasDto {
  /**
   * Transações em 1x
   */
  parcela1x: number;
  /**
   * Transações em 2x
   */
  parcela2x: number;
  /**
   * Transações em 3x
   */
  parcela3x: number;
  /**
   * Transações em 4x
   */
  parcela4x: number;
  /**
   * Transações em 5x
   */
  parcela5x: number;
  /**
   * Transações em 6x
   */
  parcela6x: number;
  /**
   * Transações em 7x
   */
  parcela7x: number;
  /**
   * Transações em 8x
   */
  parcela8x: number;
  /**
   * Transações em 9x
   */
  parcela9x: number;
  /**
   * Transações em 10x
   */
  parcela10x: number;
  /**
   * Transações em 11x
   */
  parcela11x: number;
  /**
   * Transações em 12x
   */
  parcela12x: number;
}
