/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface EditPatrimonioRequest {
  /**
   * Descrição do patrimônio
   */
  descricao?: string;
  /**
   * Tipo do patrimônio
   */
  tipo?: EditPatrimonioRequest.TipoEnum;
  /**
   * Categoria do patrimônio
   */
  categoria?: EditPatrimonioRequest.CategoriaEnum;
  /**
   * Valor atual do patrimônio
   */
  valorAtual?: number;
  /**
   * Valor inicial/aquisição do patrimônio
   */
  valorInicial?: number;
  /**
   * Data de aquisição do patrimônio
   */
  dataAquisicao?: string;
  /**
   * Observações sobre o patrimônio
   */
  observacoes?: string;
  /**
   * Saldo devedor (obrigatório para passivos)
   */
  saldoDevedor?: number;
  /**
   * Taxa de juros mensal (%)
   */
  taxaJuros?: number;
  /**
   * Data de vencimento (para passivos)
   */
  dataVencimento?: string;
  /**
   * ID da pessoa (opcional)
   */
  pessoaId?: string;
}
export namespace EditPatrimonioRequest {
  export type TipoEnum = "ativo" | "passivo";
  export const TipoEnum = {
    Ativo: "ativo" as TipoEnum,
    Passivo: "passivo" as TipoEnum,
  };
  export type CategoriaEnum =
    | "imovel"
    | "veiculo"
    | "investimento"
    | "disponivel"
    | "outros_ativos"
    | "financiamento"
    | "emprestimo"
    | "divida"
    | "outros_passivos";
  export const CategoriaEnum = {
    Imovel: "imovel" as CategoriaEnum,
    Veiculo: "veiculo" as CategoriaEnum,
    Investimento: "investimento" as CategoriaEnum,
    Disponivel: "disponivel" as CategoriaEnum,
    OutrosAtivos: "outros_ativos" as CategoriaEnum,
    Financiamento: "financiamento" as CategoriaEnum,
    Emprestimo: "emprestimo" as CategoriaEnum,
    Divida: "divida" as CategoriaEnum,
    OutrosPassivos: "outros_passivos" as CategoriaEnum,
  };
}
