/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnumOption } from "./enumOption";

export interface Enums {
  tipoCategoria: Array<EnumOption>;
  tipoTransacao: Array<EnumOption>;
  tipoPatrimonio: Array<EnumOption>;
  formaPagamento: Array<EnumOption>;
}
