/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface EvolucaoItem {
  valorAtual: number;
  valorMesAnterior: number;
  variacao: number;
  percentual: number;
  tendencia: EvolucaoItem.TendenciaEnum;
}
export namespace EvolucaoItem {
  export type TendenciaEnum = "alta" | "baixa" | "estavel";
  export const TendenciaEnum = {
    Alta: "alta" as TendenciaEnum,
    Baixa: "baixa" as TendenciaEnum,
    Estavel: "estavel" as TendenciaEnum,
  };
}
