/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface EvolucaoMensalDto {
  /**
   * Ano
   */
  ano: number;
  /**
   * Mês
   */
  mes: number;
  /**
   * Total de receitas
   */
  receitas: number;
  /**
   * Total de despesas
   */
  despesas: number;
  /**
   * Saldo do mês
   */
  saldo: number;
  /**
   * Número de transações
   */
  numeroTransacoes: number;
}
