/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DistribuicaoParcelasDto } from "./distribuicaoParcelasDto";
import { FormaPagamentoAvistaDto } from "./formaPagamentoAvistaDto";
import { FormaPagamentoParceladoDto } from "./formaPagamentoParceladoDto";

export interface FormaPagamentoAnalyticsDto {
  /**
   * Dados de transações à vista
   */
  avista: FormaPagamentoAvistaDto;
  /**
   * Dados de transações parceladas
   */
  parcelado: FormaPagamentoParceladoDto;
  /**
   * Distribuição por número de parcelas
   */
  distribuicaoParcelas: DistribuicaoParcelasDto;
}
