/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface FormaPagamentoParceladoDto {
  /**
   * Número de transações parceladas
   */
  numeroTransacoes: number;
  /**
   * Valor total parcelado
   */
  valorTotal: number;
  /**
   * Percentual das transações parceladas
   */
  percentual: number;
  /**
   * Média de parcelamento
   */
  mediaParcelamento: number;
}
