/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnalyticsMeiosPagamentoDataDto } from "./analyticsMeiosPagamentoDataDto";

export interface GetAnalyticsMeiosPagamentoResponse {
  /**
   * Mensagem de resposta
   */
  message: string;
  /**
   * Dados de analytics por meio de pagamento
   */
  data: AnalyticsMeiosPagamentoDataDto;
}
