/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DespesaPorCategoria } from "./despesaPorCategoria";
import { DespesaPorMes } from "./despesaPorMes";
import { DespesaPorCategoriaPorMes } from "./despesaPorCategoriaPorMes";
import { ReceitaPorMes } from "./receitaPorMes";

export interface GetResumoFinanceiro {
  /**
   * ID do resumo financeiro
   */
  id: number;
  totalReceitasAno: number;
  totalDespesasAno: number;
  saldoAno: number;
  patrimonio: number;
  receitasPorMes: Array<ReceitaPorMes>;
  despesasPorMes: Array<DespesaPorMes>;
  despesasPorCategoria: Array<DespesaPorCategoria>;
  despesasPorCategoriaPorMes: Array<DespesaPorCategoriaPorMes>;
  /**
   * Data da última atualização
   */
  atualizadoEm: string;
}
