/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DespesaPorCategoriaAno } from "./despesaPorCategoriaAno";
import { DespesaPorMes } from "./despesaPorMes";
import { DespesaPorCategoriaMes } from "./despesaPorCategoriaMes";
import { ReceitaPorMes } from "./receitaPorMes";

export interface GetResumoFinanceiro {
  /**
   * ID do resumo financeiro
   */
  id: number;
  receitasAno: number;
  despesasAno: number;
  saldoAno: number;
  patrimonio: number;
  receitasMes: Array<ReceitaPorMes>;
  despesasMes: Array<DespesaPorMes>;
  despesasPorCategoriaAno: Array<DespesaPorCategoriaAno>;
  despesasPorCategoriaMes: Array<DespesaPorCategoriaMes>;
  /**
   * Data da última atualização
   */
  atualizadoEm: string;
}
