/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface InsightFinanceiroDto {
  /**
   * Tipo do insight
   */
  tipo: InsightFinanceiroDto.TipoEnum;
  /**
   * Título do insight
   */
  titulo: string;
  /**
   * Descrição detalhada
   */
  descricao: string;
  /**
   * Valor relacionado ao insight
   */
  valor?: number;
  /**
   * Ação recomendada
   */
  acao?: string;
}
export namespace InsightFinanceiroDto {
  export type TipoEnum = "positivo" | "neutro" | "atencao" | "critico";
  export const TipoEnum = {
    Positivo: "positivo" as TipoEnum,
    Neutro: "neutro" as TipoEnum,
    Atencao: "atencao" as TipoEnum,
    Critico: "critico" as TipoEnum,
  };
}
