/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface LembreteTransacaoDto {
  /**
   * ID do lembrete
   */
  id: string;
  /**
   * Descrição do lembrete
   */
  descricao: string;
  /**
   * Data prevista
   */
  data: string;
  /**
   * Valor previsto
   */
  valor: number;
  /**
   * Categoria relacionada
   */
  categoria: string;
  /**
   * Status do lembrete
   */
  status: LembreteTransacaoDto.StatusEnum;
}
export namespace LembreteTransacaoDto {
  export type StatusEnum = "pendente" | "realizado" | "atrasado";
  export const StatusEnum = {
    Pendente: "pendente" as StatusEnum,
    Realizado: "realizado" as StatusEnum,
    Atrasado: "atrasado" as StatusEnum,
  };
}
