/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface LinhaConfirmacao {
  /**
   * Data (YYYY-MM-DD)
   */
  data: string;
  descricao: string;
  valor: number;
  /**
   * Categoria escolhida/confirmada
   */
  categoriaId?: string;
  pessoaId?: string;
  meioPagamentoId?: string;
  /**
   * Forma de pagamento escolhida na revisão (default: sem valor)
   */
  formaPagamento?: LinhaConfirmacao.FormaPagamentoEnum;
  /**
   * Se true e formaPagamento for parcelada (parcelaNx), cria as N parcelas: a
   * 1ª como \"paga\" (esta fatura) e as futuras como \"pendente\" (projeção),
   * uma por mês. Se false/ausente, cria só esta linha.
   */
  propagarParcelas?: boolean;
}
export namespace LinhaConfirmacao {
  export type FormaPagamentoEnum =
    | "avista"
    | "parcela1x"
    | "parcela2x"
    | "parcela3x"
    | "parcela4x"
    | "parcela5x"
    | "parcela6x"
    | "parcela7x"
    | "parcela8x"
    | "parcela9x"
    | "parcela10x"
    | "parcela11x"
    | "parcela12x";
  export const FormaPagamentoEnum = {
    Avista: "avista" as FormaPagamentoEnum,
    Parcela1x: "parcela1x" as FormaPagamentoEnum,
    Parcela2x: "parcela2x" as FormaPagamentoEnum,
    Parcela3x: "parcela3x" as FormaPagamentoEnum,
    Parcela4x: "parcela4x" as FormaPagamentoEnum,
    Parcela5x: "parcela5x" as FormaPagamentoEnum,
    Parcela6x: "parcela6x" as FormaPagamentoEnum,
    Parcela7x: "parcela7x" as FormaPagamentoEnum,
    Parcela8x: "parcela8x" as FormaPagamentoEnum,
    Parcela9x: "parcela9x" as FormaPagamentoEnum,
    Parcela10x: "parcela10x" as FormaPagamentoEnum,
    Parcela11x: "parcela11x" as FormaPagamentoEnum,
    Parcela12x: "parcela12x" as FormaPagamentoEnum,
  };
}
