/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface LinhaConfirmacao {
  /**
   * Data (YYYY-MM-DD)
   */
  data: string;
  descricao: string;
  valor: number;
  /**
   * Categoria escolhida/confirmada
   */
  categoriaId?: string;
  pessoaId?: string;
  meioPagamentoId?: string;
}
