/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { CategoriaSugerida } from "./categoriaSugerida";

export interface LinhaImportacao {
  /**
   * Data (YYYY-MM-DD)
   */
  data: string;
  descricao: string;
  /**
   * Valor absoluto (sempre positivo)
   */
  valor: number;
  /**
   * Derivado do sinal do valor no extrato
   */
  tipo: LinhaImportacao.TipoEnum;
  /**
   * Categoria sugerida pelo histórico (editável). Null se não houver palpite.
   */
  categoriaSugerida?: CategoriaSugerida | null;
  /**
   * True se parece já lançada (mesma data + valor). Vem desmarcada.
   */
  possivelDuplicada: boolean;
  /**
   * Se a linha está marcada para importar (false por padrão se duplicada).
   */
  incluir: boolean;
}
export namespace LinhaImportacao {
  export type TipoEnum = "receita" | "despesa";
  export const TipoEnum = {
    Receita: "receita" as TipoEnum,
    Despesa: "despesa" as TipoEnum,
  };
}
