/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface MeioPagamentoAnalyticsDto {
  /**
   * ID do meio de pagamento
   */
  id: string;
  /**
   * Nome do meio de pagamento
   */
  nome: string;
  /**
   * Valor total movimentado
   */
  valorTotal: number;
  /**
   * Número de transações
   */
  numeroTransacoes: number;
  /**
   * Percentual do total
   */
  percentualDoTotal: number;
  /**
   * Valor médio por transação
   */
  valorMedio: number;
}
