/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface MeioPagamento {
  id: string;
  nome: string;
  /**
   * Se o meio de pagamento é favorito
   */
  favorito: boolean;
  /**
   * Tipo do meio de pagamento
   */
  tipo: MeioPagamento.TipoEnum;
  /**
   * Dia (1-31) de vencimento da fatura (só para tipo credito)
   */
  diaVencimento?: number | null;
  /**
   * Número de transações usando este meio
   */
  totalLancamentos: number;
  createdAt: string;
}
export namespace MeioPagamento {
  export type TipoEnum =
    | "credito"
    | "debito"
    | "pix"
    | "dinheiro"
    | "boleto"
    | "outro";
  export const TipoEnum = {
    Credito: "credito" as TipoEnum,
    Debito: "debito" as TipoEnum,
    Pix: "pix" as TipoEnum,
    Dinheiro: "dinheiro" as TipoEnum,
    Boleto: "boleto" as TipoEnum,
    Outro: "outro" as TipoEnum,
  };
}
