/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DiasSemGastosDto } from "./diasSemGastosDto";
import { MaiorGastoMesDto } from "./maiorGastoMesDto";

export interface MetricasAvancadasDto {
  /**
   * Média de despesas diárias
   */
  mediaDespesasDiarias: number;
  /**
   * Média mensal dos últimos 6 meses
   */
  mediaMensalUltimos6Meses: number;
  /**
   * Variação percentual dos últimos 6 meses
   */
  variacao6Meses: number;
  /**
   * Maior gasto do mês
   */
  maiorGastoMes: MaiorGastoMesDto;
  /**
   * Estatísticas de dias sem gastos
   */
  diasSemGastos: DiasSemGastosDto;
}
