/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UltimaTransacaoDto } from "./ultimaTransacaoDto";

export interface OrcamentoCategoriaDto {
  /**
   * ID da categoria
   */
  categoriaId: string;
  /**
   * Nome da categoria
   */
  categoriaNome: string;
  /**
   * Ícone da categoria
   */
  categoriaIcone: string;
  /**
   * Cor da categoria
   */
  categoriaCor: string;
  /**
   * Valor orçado (baseado no teto)
   */
  valorOrcado: number;
  /**
   * Valor realizado
   */
  valorRealizado: number;
  /**
   * Percentual utilizado
   */
  percentualUtilizado: number;
  /**
   * Status do orçamento
   */
  status: OrcamentoCategoriaDto.StatusEnum;
  /**
   * Saldo restante
   */
  saldoRestante: number;
  /**
   * Projeção para o final do mês
   */
  projecaoMes: number;
  /**
   * Últimas transações da categoria
   */
  ultimasTransacoes: Array<UltimaTransacaoDto>;
}
export namespace OrcamentoCategoriaDto {
  export type StatusEnum = "dentro" | "atencao" | "ultrapassado";
  export const StatusEnum = {
    Dentro: "dentro" as StatusEnum,
    Atencao: "atencao" as StatusEnum,
    Ultrapassado: "ultrapassado" as StatusEnum,
  };
}
