/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface OrcamentoGeralDto {
  /**
   * Valor orçado para o mês
   */
  valorOrcado: number;
  /**
   * Valor realizado até o momento
   */
  valorRealizado: number;
  /**
   * Percentual utilizado do orçamento
   */
  percentualUtilizado: number;
  /**
   * Saldo restante
   */
  saldoRestante: number;
  /**
   * Dias restantes no mês
   */
  diasRestantes: number;
  /**
   * Média de gasto diário atual
   */
  mediaGastoDiario: number;
  /**
   * Média permitida diária para não ultrapassar
   */
  mediaPermitidaDiaria: number;
  /**
   * Projeção final do mês
   */
  projecaoFinal: number;
}
