/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PadraoDiarioDto {
  /**
   * Dia da semana
   */
  diaSemana: string;
  /**
   * Número de transações
   */
  numeroTransacoes: number;
  /**
   * Valor médio das transações
   */
  valorMedio: number;
  /**
   * Valor total do dia
   */
  valorTotal: number;
  /**
   * Horário preferido
   */
  horarioPreferido: PadraoDiarioDto.HorarioPreferidoEnum;
}
export namespace PadraoDiarioDto {
  export type HorarioPreferidoEnum = "manha" | "tarde" | "noite";
  export const HorarioPreferidoEnum = {
    Manha: "manha" as HorarioPreferidoEnum,
    Tarde: "tarde" as HorarioPreferidoEnum,
    Noite: "noite" as HorarioPreferidoEnum,
  };
}
