/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PaginationMeta {
  /**
   * Página atual
   */
  page: number;
  /**
   * Limite de itens por página
   */
  perPage: number;
  /**
   * Total de itens encontrados
   */
  total: number;
  lastPage: number;
}
