/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ParcelaAbertaDto {
  /**
   * ID da transação original
   */
  transacaoOriginalId: string;
  /**
   * Descrição da compra
   */
  descricao: string;
  /**
   * Valor total da compra
   */
  valorTotal: number;
  /**
   * Forma de pagamento
   */
  formaPagamento: string;
  /**
   * Parcela atual
   */
  parcelaAtual: number;
  /**
   * Total de parcelas
   */
  totalParcelas: number;
  /**
   * Valor de cada parcela
   */
  valorParcela: number;
  /**
   * Próximo vencimento
   */
  proximoVencimento?: string;
  /**
   * Parcelas restantes
   */
  parcelasRestantes: number;
  /**
   * Valor restante total
   */
  valorRestante: number;
}
