/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Patrimonio {
  id: string;
  descricao: string;
  tipo: Patrimonio.TipoEnum;
  /**
   * Tipo formatado com label
   */
  tipoFormatado: string;
  categoria: Patrimonio.CategoriaEnum;
  /**
   * Categoria formatada com label
   */
  categoriaFormatada: string;
  valorAtual: number;
  valorInicial?: number;
  dataAquisicao: string;
  observacoes?: string;
  saldoDevedor?: number;
  taxaJuros?: number;
  dataVencimento?: string;
  /**
   * Meses restantes até o vencimento (calculado)
   */
  mesesRestantes?: number;
  pessoaId?: string;
  createdAt: string;
  updatedAt: string;
}
export namespace Patrimonio {
  export type TipoEnum = "ativo" | "passivo";
  export const TipoEnum = {
    Ativo: "ativo" as TipoEnum,
    Passivo: "passivo" as TipoEnum,
  };
  export type CategoriaEnum =
    | "imovel"
    | "veiculo"
    | "investimento"
    | "disponivel"
    | "outros_ativos"
    | "financiamento"
    | "emprestimo"
    | "divida"
    | "outros_passivos";
  export const CategoriaEnum = {
    Imovel: "imovel" as CategoriaEnum,
    Veiculo: "veiculo" as CategoriaEnum,
    Investimento: "investimento" as CategoriaEnum,
    Disponivel: "disponivel" as CategoriaEnum,
    OutrosAtivos: "outros_ativos" as CategoriaEnum,
    Financiamento: "financiamento" as CategoriaEnum,
    Emprestimo: "emprestimo" as CategoriaEnum,
    Divida: "divida" as CategoriaEnum,
    OutrosPassivos: "outros_passivos" as CategoriaEnum,
  };
}
