/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuickStatDto } from "./quickStatDto";

export interface QuickStatsDataDto {
  /**
   * Gasto da semana atual
   */
  gastoSemana: QuickStatDto;
  /**
   * Economia do mês
   */
  economiaMes: QuickStatDto;
  /**
   * Maior categoria do mês
   */
  maiorCategoria: QuickStatDto;
  /**
   * Dias sem gastos
   */
  diasSemGastos: QuickStatDto;
  /**
   * Maior transação do mês
   */
  transacaoMaior: QuickStatDto;
  /**
   * Comparativo com o ano
   */
  comparativoAno: QuickStatDto;
}
