/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuickStatDtoValor } from "./quickStatDtoValor";
import { VariacaoQuickStatDto } from "./variacaoQuickStatDto";

export interface QuickStatDto {
  /**
   * Título do stat
   */
  titulo: string;
  valor: QuickStatDtoValor;
  /**
   * Subtítulo ou informação adicional
   */
  subtitulo?: string;
  /**
   * Variação em relação ao período anterior
   */
  variacao?: VariacaoQuickStatDto;
  /**
   * Ícone para o stat
   */
  icone?: string;
  /**
   * Cor para destacar o stat
   */
  cor?: string;
}
