/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaginationMeta } from "./paginationMeta";
import { RelatorioTransacoesResponse } from "./relatorioTransacoesResponse";
import { TransacoesResume } from "./transacoesResume";

export interface RelatorioTrasacoesPaginatedData {
  meta: PaginationMeta;
  rows: Array<RelatorioTransacoesResponse>;
  resume: TransacoesResume;
}
