/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { DistribuicaoItem } from "./distribuicaoItem";
import type { EvolucaoDetalhada } from "./evolucaoDetalhada";
import type { EvolucaoItem } from "./evolucaoItem";

export interface ResumoPatrimonio {
  dataReferencia: string;
  /**
   * Saldo disponível em conta (calculado das transações: receitas - despesas)
   */
  saldoDisponivel: number;
  /**
   * Total de ativos (incluindo saldo disponível)
   */
  totalAtivos: number;
  totalPassivos: number;
  /**
   * Patrimônio líquido (totalAtivos - totalPassivos)
   */
  patrimonioLiquido: number;
  /**
   * Evolução do patrimônio líquido
   */
  evolucao: EvolucaoDetalhada;
  /**
   * Evolução detalhada dos ativos
   */
  evolucaoAtivos: EvolucaoItem;
  /**
   * Evolução detalhada dos passivos
   */
  evolucaoPassivos: EvolucaoItem;
  distribuicaoAtivos: Array<DistribuicaoItem>;
  distribuicaoPassivos: Array<DistribuicaoItem>;
}
