/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface SaudeFinanceiraDto {
  /**
   * Status da saúde financeira
   */
  status: SaudeFinanceiraDto.StatusEnum;
  /**
   * Pontuação de 0-100
   */
  pontuacao: number;
  /**
   * Fatores que influenciam a pontuação
   */
  fatores: object;
}
export namespace SaudeFinanceiraDto {
  export type StatusEnum = "saudavel" | "atencao" | "critico" | "excelente";
  export const StatusEnum = {
    Saudavel: "saudavel" as StatusEnum,
    Atencao: "atencao" as StatusEnum,
    Critico: "critico" as StatusEnum,
    Excelente: "excelente" as StatusEnum,
  };
}
