/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface TransacaoRecorrenteDto {
  /**
   * Padrão identificado
   */
  padrao: string;
  /**
   * Frequência identificada
   */
  frequencia: TransacaoRecorrenteDto.FrequenciaEnum;
  /**
   * Última ocorrência
   */
  ultimaOcorrencia: string;
  /**
   * Próxima previsão
   */
  proximaPrevisao: string;
  /**
   * Valor médio das ocorrências
   */
  valorMedio: number;
  /**
   * Categoria mais comum
   */
  categoria: string;
  /**
   * Confiança da identificação (0-100%)
   */
  confianca: number;
}
export namespace TransacaoRecorrenteDto {
  export type FrequenciaEnum = "semanal" | "quinzenal" | "mensal";
  export const FrequenciaEnum = {
    Semanal: "semanal" as FrequenciaEnum,
    Quinzenal: "quinzenal" as FrequenciaEnum,
    Mensal: "mensal" as FrequenciaEnum,
  };
}
