/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { PaginationMeta } from "./paginationMeta";
import type { TransacaoResponse } from "./transacaoResponse";
import type { TransacoesResume } from "./transacoesResume";

export interface TransacaoPaginatedData {
  meta: PaginationMeta;
  rows: Array<TransacaoResponse>;
  resume: TransacoesResume;
}
