/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategoriaCalendario } from "./categoriaCalendario";
import { MeioPagamentoCalendario } from "./meioPagamentoCalendario";
import { PessoaCalendario } from "./pessoaCalendario";

export interface TransacaoCalendario {
  id: string;
  descricao: string;
  /**
   * Valor em centavos
   */
  valor: number;
  categoria: CategoriaCalendario | null;
  pessoa: PessoaCalendario | null;
  meioPagamento: MeioPagamentoCalendario | null;
  formaPagamento: string | null;
  /**
   * Flag para mostrar transação no calendário como lembrete
   */
  lembrarMe: boolean;
  tipo: TransacaoCalendario.TipoEnum;
}
export namespace TransacaoCalendario {
  export type TipoEnum = "receita" | "despesa";
  export const TipoEnum = {
    Receita: "receita" as TipoEnum,
    Despesa: "despesa" as TipoEnum,
  };
}
