/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ValoresProjecaoDto {
  /**
   * Receitas realizadas até agora
   */
  receitasRealizadas: number;
  /**
   * Despesas realizadas até agora
   */
  despesasRealizadas: number;
  /**
   * Projeção de receitas para o mês
   */
  receitasProjetadas: number;
  /**
   * Projeção de despesas para o mês
   */
  despesasProjetadas: number;
  /**
   * Saldo projetado para o mês
   */
  saldoProjetado: number;
}
