/**
 * API de finanças M&J
 * API de controle financeiro do Júnior e da Vivi
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface VariacaoQuickStatDto {
  /**
   * Valor da variação
   */
  valor: number;
  /**
   * Tipo da variação
   */
  tipo: VariacaoQuickStatDto.TipoEnum;
  /**
   * Período de comparação
   */
  periodo: string;
}
export namespace VariacaoQuickStatDto {
  export type TipoEnum = "positiva" | "negativa" | "neutra";
  export const TipoEnum = {
    Positiva: "positiva" as TipoEnum,
    Negativa: "negativa" as TipoEnum,
    Neutra: "neutra" as TipoEnum,
  };
}
